print("Hello, world!")
print("Salom Dunyo")
print('Hayrli tong!')
print(2+3+4)
my_string= "HELLO WORLD"
print(my_string)
print ('Men "DELL" markasidagi notebook oldim')
print("""Odami ersang, demagil odami,
Oniki, yo'q xalq g'amidin g'ami""")
print("Odami ersang, demagil odami,\nOniki, yo'q xalq g'amidin g'ami")
print("Odami ersang, demagil odami,\nOniki, yo\'q xalq g\'amidin g\'ami")
print(20/5)
print(20//5)
print(5**3)
print(16%5)
print ('To\'qqizning kvadrati' ,9**3, 'ga teng')
#Amaliy Topshiriqlar 1-dars python.sariq.dev
print('1-dars uchun amaliy topshiriqlar!')
print('"Nexia", "Tico", \'Damas\' ko\'rganlar qilar havas')
print('5 ning 4-darajasini toping')
print('5 ning 4-chi darajasi', 5**4, 'ga teng')
print('22 ni 4 ga bo\'lganda qancha qoldiq qoladi?')
print('22 ni 4 ga bo\'lgandagi qoldiq', 22%4, 'ga teng')
print('Tomonlari 125 ga teng kvadratning yuzi va perimetrini toping')
print('Kavdrat yuzi S=a*b', 125*125, 'ga teng Premetri P=2*(a+b)', (125+125)*2, 'ga teng')
print('Diametri 12 ga teng bo\'lgan doiraning yuzini toping  PI ( 3.14 deb oling)')
print('Doirani yuzi ushbu formuladan topiladi S=pi*r*r', 6**2*3.14, 'ga teng')
print('Katetlari 6 va 7 bo\'lgan to\'g\'ri burchakli uchburchakning gipotenuzasini toping (Pifagor teoremasidan foydalaning)')
print('Pifagor formulasidan katetlar \'a\' va \'b\' katetlar hisoblanadi \'c\' esa gipatenuza c^2=a^2+b^2 c=',(6**2+7**2)**(1/2),'ga teng')
